/**
 * Stellr Sign Interpretations
 * 
 * Database of all 36 interpretations (12 signs × 3 types).
 * Each interpretation is written to feel personal and specific.
 */

export const interpretations: Record<string, Record<string, string>> = {
  aries: {
    sun: "You are someone who moves through the world with directness and courage. You don't wait for permission — you take initiative, often before others even see the opportunity. There's a freshness to your energy, a sense that you're always ready to begin something new. You're at your best when you're leading, pioneering, or breaking ground. Conflict doesn't scare you; in fact, you sometimes need it to feel alive. Your challenge is learning when to pause, when to let others catch up, and when the battle isn't worth fighting.",
    moon: "Emotionally, you process quickly and honestly. When something bothers you, it shows — you don't have the patience (or desire) to hide your feelings. You need freedom to feel what you feel without judgment, and you respect others who do the same. Your emotional instinct is to act, to move, to express. You're not someone who sits with difficult emotions for long; you'd rather confront them head-on and move through. What you need most is space to be impulsive without shame.",
    rising: "People experience you as bold, energetic, someone who takes initiative. You walk into rooms like you belong there — not arrogantly, but with a natural confidence that says, \"I'm here.\" First impressions of you often include words like \"direct,\" \"dynamic,\" or \"intense.\" You have a physical presence that commands attention, even when you're not trying. People sense that you're someone who gets things done, who doesn't overthink, who acts.",
  },
  taurus: {
    sun: "You are someone who values stability, beauty, and the tangible. You move through the world at your own pace — not slow, but deliberate. You don't rush into things; you prefer to build slowly, surely, something that lasts. There's a sensuality to you, a deep appreciation for the physical world: good food, comfortable spaces, beautiful objects. You're loyal to a fault, and once you commit, you're in for the long haul. Your challenge is learning to adapt when life demands change, and to let go when holding on no longer serves you.",
    moon: "Emotionally, you need consistency and comfort. You're not someone who thrives on drama or sudden shifts — you want to know what to expect, and you want to feel safe. When you're upset, you tend to withdraw and process privately, often through physical comfort: food, rest, nature. You feel deeply, but you show it through actions rather than words. What you need most is patience — from others and from yourself — and the understanding that your steady love is a rare and valuable thing.",
    rising: "People experience you as grounded, calm, someone they can rely on. You have a presence that's both warm and solid — people feel safe around you, like they can exhale. First impressions of you often include words like \"stable,\" \"gentle,\" or \"reliable.\" You move with a certain grace, a deliberate quality that suggests you're not easily rattled. People sense that you're someone who appreciates beauty, who takes their time, who can be trusted.",
  },
  gemini: {
    sun: "You are someone who thinks faster than most people can talk. Your mind is always moving, making connections, jumping from idea to idea. You're curious about everything — not in a shallow way, but in a genuine, insatiable way. You communicate easily, adapting your style to whoever you're with. You're at your best when you're learning, teaching, writing, or connecting people and ideas. Your challenge is learning to go deep, to sit with one thing long enough to truly master it, and to recognize when your restlessness is avoidance.",
    moon: "Emotionally, you process through thinking and talking. You need to verbalize what you feel, to turn it into words, to make sense of it intellectually. You're not someone who sits in heavy emotions for long — you'd rather analyze them, discuss them, understand them. You need mental stimulation even in your emotional life; boredom is your enemy. What you need most is someone who can keep up with your mind, who won't be overwhelmed by your need to process out loud.",
    rising: "People experience you as curious, adaptable, someone who's easy to talk to. You have a lightness to your presence, a quickness that makes you seem younger than you are. First impressions of you often include words like \"witty,\" \"engaging,\" or \"versatile.\" You move through the world with a certain playfulness, and people sense that you're someone who knows a little bit about everything. You come across as approachable, interested, interested in them.",
  },
  cancer: {
    sun: "You are someone who feels everything deeply, even when you don't show it. You have a natural ability to sense what others are feeling, often before they say it. You're protective of the people you love, sometimes to the point of smothering. You move through the world with a kind of emotional intelligence that others find both comforting and unnerving. You're at your best when you're nurturing, creating, or building a home — literal or metaphorical. Your challenge is learning to set boundaries, to protect your own energy, and to recognize when you're taking on emotions that aren't yours.",
    moon: "Emotionally, you are depth itself. You feel things at a level that sometimes overwhelms you, and you've learned to protect yourself by retreating into your shell. You need safety to open up, but once you feel safe, you're incredibly loyal and nurturing. You process emotions through memory, through the past, through the people and places that shaped you. What you need most is a safe harbor, someone who won't judge your sensitivity and who understands that your depth is a gift, not a burden.",
    rising: "People experience you as warm, intuitive, someone who makes them feel seen. You have a softness to your presence that invites trust — people tell you things they wouldn't tell others. First impressions of you often include words like \"nurturing,\" \"gentle,\" or \"intuitive.\" You move through the world with a certain tenderness, and people sense that you're someone who cares, who feels, who remembers. You come across as safe, as someone they can be vulnerable with.",
  },
  leo: {
    sun: "You are someone who radiates warmth and confidence, whether you mean to or not. You're at your best when you're creating, performing, or leading — you need to be seen, and you need to create something that matters. You're generous to a fault, loyal beyond reason, and you love deeply and dramatically. You don't do anything halfway; when you commit, you commit fully. Your challenge is learning that you don't always have to be the center of attention, that others need to shine too, and that your worth isn't dependent on external validation.",
    moon: "Emotionally, you need to feel special, appreciated, and seen. You process feelings through expression — you need to create, to perform, to share. You're warm and generous with your love, but you also need to feel loved in return, visibly and vocally. You don't handle rejection well; it cuts deeper for you than you let on. What you need most is someone who celebrates you, who sees your light and doesn't try to dim it, who understands that your need for attention is really a need for connection.",
    rising: "People experience you as confident, warm, someone who lights up the room. You have a presence that's both magnetic and generous — people are drawn to you, and you make them feel good about themselves. First impressions of you often include words like \"charismatic,\" \"bold,\" or \"warm.\" You move through the world with a certain flair, and people sense that you're someone who knows how to enjoy life. You come across as someone who's comfortable being seen, who doesn't shrink.",
  },
  virgo: {
    sun: "You are someone who notices what others miss. You have a sharp eye for detail, a mind that catalogs and categorizes, and a desire to make things better — for yourself and for others. You're at your best when you're solving problems, improving systems, or helping people in practical ways. You're humble about your abilities, sometimes to a fault; you don't always recognize how much you contribute. Your challenge is learning to see the forest for the trees, to accept imperfection (in yourself and others), and to recognize when \"good enough\" is actually good enough.",
    moon: "Emotionally, you process through analysis and service. You need to feel useful, to be helpful, to make things better. When you're upset, you tend to focus on practical solutions rather than sitting with the feeling. You show love through acts of service — you notice what people need and you provide it, often before they ask. What you need most is someone who appreciates your care, who doesn't take it for granted, and who reminds you that you're loved for who you are, not just for what you do.",
    rising: "People experience you as competent, thoughtful, someone who pays attention. You have a presence that's both humble and capable — people trust you with details, with tasks, with things that matter. First impressions of you often include words like \"organized,\" \"helpful,\" or \"precise.\" You move through the world with a certain efficiency, and people sense that you're someone who gets things done, who notices what needs to be done, who can be counted on.",
  },
  libra: {
    sun: "You are someone who searches for balance, harmony, and fairness. You have a natural ability to see multiple perspectives, which makes you an excellent mediator and friend. You're drawn to beauty, to art, to relationships — you need connection to feel whole. You're at your best when you're creating harmony, making things beautiful, or bringing people together. Your challenge is learning to make decisions without endless deliberation, to honor your own needs even when they conflict with others', and to recognize that conflict isn't always bad.",
    moon: "Emotionally, you need harmony and connection. You process feelings through relationships — you need to talk, to share, to understand how others feel. You're uncomfortable with conflict, not because you're weak, but because you genuinely believe there's usually a middle ground. You show love through partnership, through consideration, through the effort to understand. What you need most is someone who values fairness as much as you do, who won't take advantage of your desire to please, and who reminds you that your needs matter too.",
    rising: "People experience you as charming, diplomatic, someone who's easy to be around. You have a presence that's both graceful and considerate — people feel heard when they're with you. First impressions of you often include words like \"polite,\" \"balanced,\" or \"gracious.\" You move through the world with a certain elegance, and people sense that you're someone who values beauty, who cares about fairness, who knows how to make others feel comfortable.",
  },
  scorpio: {
    sun: "You are someone who feels things at a depth others rarely reach. You don't do surface-level; you want to know the truth, the real truth, even when it's uncomfortable. You're intensely loyal, fiercely protective, and you have a kind of emotional courage that most people don't possess. You're at your best when you're transforming, healing, or diving into the depths of something — a relationship, a mystery, yourself. Your challenge is learning to trust, to let go of control, and to recognize that vulnerability isn't weakness.",
    moon: "Emotionally, you are intensity itself. You feel everything deeply, sometimes overwhelmingly so, and you've learned to protect yourself by controlling what you show. You need trust to open up, but once you trust, you're all in. You process emotions through transformation — you need to dig, to understand, to evolve. What you need most is someone who isn't afraid of your depth, who won't try to make you \"lighter,\" and who understands that your intensity is a form of love.",
    rising: "People experience you as intense, magnetic, someone who sees through things. You have a presence that's both quiet and powerful — people sense there's more to you than you show. First impressions of you often include words like \"mysterious,\" \"perceptive,\" or \"strong.\" You move through the world with a certain stillness, and people sense that you're someone who observes, who knows, who doesn't miss much. You come across as someone who can be trusted with secrets, who won't flinch from the truth.",
  },
  sagittarius: {
    sun: "You are someone who needs freedom, exploration, and meaning. You move through the world with optimism, with a belief that there's always more to discover. You're at your best when you're learning, traveling, teaching, or expanding your horizons. You're honest to a fault, sometimes brutally so, and you value truth over comfort. Your challenge is learning to commit, to sit with discomfort, and to recognize that depth sometimes requires staying in one place long enough to find it.",
    moon: "Emotionally, you need freedom and honesty. You process feelings through exploration — you need to move, to learn, to understand the bigger picture. You're optimistic by nature, and you tend to look forward rather than back. You show love through adventure, through sharing experiences, through encouraging others to grow. What you need most is someone who won't try to tie you down, who understands your need for space, and who will explore life with you rather than trying to keep you in one place.",
    rising: "People experience you as optimistic, adventurous, someone who's fun to be around. You have a presence that's both enthusiastic and open — people feel energized by you. First impressions of you often include words like \"friendly,\" \"adventurous,\" or \"honest.\" You move through the world with a certain lightness, and people sense that you're someone who's always looking forward, who believes in possibilities, who won't judge. You come across as someone who's comfortable anywhere, who's ready for anything.",
  },
  capricorn: {
    sun: "You are someone who builds for the long term. You have a natural understanding of structure, of time, of what it takes to create something lasting. You're at your best when you're leading, organizing, or working toward a meaningful goal. You're disciplined, responsible, and you take your commitments seriously — sometimes too seriously. Your challenge is learning to rest, to enjoy the present, and to recognize that your worth isn't dependent on your achievements.",
    moon: "Emotionally, you need structure and respect. You process feelings through action — you need to do something, to fix something, to build something. You're not someone who sits with emotions easily; you'd rather channel them into productivity. You show love through reliability, through showing up, through being someone others can count on. What you need most is someone who appreciates your steadiness, who doesn't mistake your reserve for coldness, and who reminds you that it's okay to not be in control.",
    rising: "People experience you as competent, serious, someone who gets things done. You have a presence that's both reserved and capable — people trust you with responsibility. First impressions of you often include words like \"mature,\" \"reliable,\" or \"ambitious.\" You move through the world with a certain dignity, and people sense that you're someone who takes things seriously, who can be counted on, who has standards. You come across as someone who's going somewhere, who has a plan.",
  },
  aquarius: {
    sun: "You are someone who thinks differently from most people. You have a natural ability to see the bigger picture, to understand systems, to imagine how things could be better. You're at your best when you're innovating, connecting people, or working toward something that matters. You're friendly but detached, loyal but independent, and you value freedom above almost everything else. Your challenge is learning to connect emotionally, to stay present in relationships, and to recognize that being different doesn't mean being alone.",
    moon: "Emotionally, you need freedom and intellectual stimulation. You process feelings through thinking — you need to understand them, to analyze them, to make sense of them. You're not someone who's comfortable with heavy emotional displays; you prefer to keep things light, friendly, and somewhat detached. You show love through friendship, through acceptance, through giving people space to be themselves. What you need most is someone who won't try to make you \"more emotional,\" who respects your need for independence, and who understands that your detachment isn't coldness.",
    rising: "People experience you as unique, friendly, someone who's interesting to talk to. You have a presence that's both approachable and slightly detached — people sense you're friendly, but also that you march to your own beat. First impressions of you often include words like \"quirky,\" \"open-minded,\" or \"original.\" You move through the world with a certain ease, and people sense that you're someone who doesn't judge, who accepts people as they are, who thinks differently. You come across as someone who's comfortable being themselves, who doesn't need validation.",
  },
  pisces: {
    sun: "You are someone who feels the world deeply, sometimes overwhelmingly so. You have a natural ability to empathize, to imagine, to create. You're at your best when you're creating art, helping others, or losing yourself in something beautiful. You're compassionate to a fault, sometimes absorbing others' emotions as your own. Your challenge is learning to set boundaries, to protect your energy, and to recognize that you can't save everyone.",
    moon: "Emotionally, you are ocean itself — deep, vast, sometimes overwhelming. You feel everything, often without knowing where your feelings end and others' begin. You process emotions through creativity, through imagination, through escape. You need solitude to recharge, but you also need connection to feel whole. What you need most is someone who understands your sensitivity, who won't try to make you \"stronger,\" and who provides a safe harbor for your vast emotional depths.",
    rising: "People experience you as gentle, dreamy, someone who's easy to be around. You have a presence that's both soft and slightly mysterious — people sense there's more to you than you show. First impressions of you often include words like \"kind,\" \"imaginative,\" or \"gentle.\" You move through the world with a certain grace, and people sense that you're someone who feels deeply, who creates, who understands without words. You come across as someone who's safe, who won't judge, who accepts.",
  },
};

export { signDateRanges, signElements, signModalities } from './signUtils';
